[package]
name = "gear-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.8.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false